### PR TITLE
SGA-60: Refactor 'SmartgadgetPreferenceFragment'

### PR DESCRIPTION
**Pull request by xavier-fernandez**
- Bind XML strings using the BUTTERKNIFE library
- Refactor de preference adapter to use the ViewHolder pattern
- Prefer ‘getContext()’ rather than ‘getParent()’  whether possible
- Rename all prefix named ‘obtain’ to ‘get’ in order to follow project
  conventions
- Refactor code for avoiding lines with a length greater than 120
  characters
- Avoid some possible NullPointerExceptions if the parent activity is
  not a ‘MainActivity’. (Logs an error instead)

### CODE REVIEW

**Comment by xavier-fernandez** [comment]
@abrauchli I did an amend to the commit

**Comment by xavier-fernandez** [comment]
@abrauchli Did an amend fixing the following issues:
- Replace asserts with if(whatever != null)
- Obtain typeface from XML
- Fix small issue with the XML name

**Comment by xavier-fernandez** [comment]
Did an amend cb0ee5d...44540bf

Previous commit: https://github.com/xavier-fernandez/SmartGadget-Android/commit/cb0ee5d964331d19e322fd35de9a83cc2f7bb385

**Comment by abrauchli** [comment]
merged in master

**Pull request closed without merging**
