### PR TITLE
SGA-60: Refactor the 'ScanDeviceFragment'

### PR DESCRIPTION
**Pull request by xavier-fernandez**
@abrauchli

### CODE REVIEW

**Comment by xavier-fernandez** [comment]
@abrauchli I did an amend.

**Comment by xavier-fernandez** [comment]
@abrauchli I did an amend fixing the two issues:
- Non-Global typefaces
- List synchronization on the 'add' and 'clear' methods

I also added the refactor of the 'ScanDeviceFragment' class

**Comment by xavier-fernandez** [comment]
Did an amend: e288340bd5bd5e139637e1ce775d80707b8d6e83...65246f7

Previous commit: https://github.com/xavier-fernandez/SmartGadget-Android/commit/e288340bd5bd5e139637e1ce775d80707b8d6e83

**Comment by xavier-fernandez** [comment]
@abrauchli 
Did an amend: 65246f7...edb4aad

**Comment by abrauchli** [comment]
merged in master

**Pull request closed without merging**
