### PR TITLE
Cache latest sensor measurement data

### PR DESCRIPTION
**Pull request by xavier-fernandez**
- The latest sensor measurement data is stored on the RhtSensorFacade. When
  a fragment, or a listener is registered, is automatically notified of the
  latest sensor values. Fragments will have immediatly the latest sensor data
  and will not have to wait until the Humigadget devices sends a new
  notification again.

### CODE REVIEW

**Comment by xavier-fernandez** [comment]
Did an amend: 84a787e...f406930

**Comment by xavier-fernandez** [comment]
Did an amend: f406930...270e0e9

**Comment by xavier-fernandez** [comment]
Did an amend: 270e0e9...3462cd5

**Comment by abrauchli** [comment]
merged as be51e21e52d6427aa977a0a0bed69f40b445f07e

**Pull request closed without merging**
