### PR TITLE
SGA-61: Fix 'not-running test' bug

### PR DESCRIPTION
**Pull request by xavier-fernandez**
- Refactor ‘DeviceNameDatabaseTest.java’
  - Test class extends ‘android.test.AndroidTestCase’
  - Remove test not related to the testing of the methods from the
    DeviceNameDatabase repository.
  - Annotate all asserts with messages
  - Fix some possible NullPointerExceptions
  - Fix the bug ‘SGA-61’, producing test cases not running properly

### CODE REVIEW

**Comment by abrauchli** [comment]
Code seems fine, test doesn't pass (seems unrelated)
gradle connectedAndroidTest

```
com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneSummerTest > testComfortZoneCorners[GT-I9505 - 4.4.2] FAILED 
    junit.framework.AssertionFailedError
    at com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneTest.testComfortZoneCorners(XyPlotViewComfortZoneTest.java:28)

com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneSummerTest > testComfortZoneInsideBottomLeft[GT-I9505 - 4.4.2] FAILED 
    junit.framework.AssertionFailedError
    at com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneTest.testComfortZoneInsideBottomLeft(XyPlotViewComfortZoneTest.java:56)

com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneSummerTest > testComfortZoneInsideMid[GT-I9505 - 4.4.2] FAILED 
    junit.framework.AssertionFailedError
    at com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneTest.testComfortZoneInsideMid(XyPlotViewComfortZoneTest.java:70)

com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneSummerTest > testComfortZoneInsideTopRight[GT-I9505 - 4.4.2] FAILED 
    junit.framework.AssertionFailedError
    at com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneTest.testComfortZoneInsideTopRight(XyPlotViewComfortZoneTest.java:62)

com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneSummerTest > testComfortZoneOutsideBottomRight[GT-I9505 - 4.4.2] FAILED 
    junit.framework.AssertionFailedError
    at com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneTest.testComfortZoneOutsideBottomRight(XyPlotViewComfortZoneTest.java:48)

com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneSummerTest > testComfortZoneOutsideTopLeft[GT-I9505 - 4.4.2] FAILED 
    junit.framework.AssertionFailedError
    at com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneTest.testComfortZoneOutsideTopLeft(XyPlotViewComfortZoneTest.java:38)

com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneSummerTest > testComfortZoneOutsideZero[GT-I9505 - 4.4.2] FAILED 
    junit.framework.AssertionFailedError
    at com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneTest.testComfortZoneOutsideZero(XyPlotViewComfortZoneTest.java:75)

com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneWinterTest > testComfortZoneOutsideBottomRight[GT-I9505 - 4.4.2] FAILED 
    junit.framework.AssertionFailedError
    at com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneTest.testComfortZoneOutsideBottomRight(XyPlotViewComfortZoneTest.java:48)

com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneWinterTest > testComfortZoneOutsideTopLeft[GT-I9505 - 4.4.2] FAILED 
    junit.framework.AssertionFailedError
    at com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneTest.testComfortZoneOutsideTopLeft(XyPlotViewComfortZoneTest.java:38)

com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneWinterTest > testComfortZoneOutsideZero[GT-I9505 - 4.4.2] FAILED 
    junit.framework.AssertionFailedError
    at com.sensirion.smartgadget.tests.ui.view.XyPlotViewComfortZoneTest.testComfortZoneOutsideZero(XyPlotViewComfortZoneTest.java:75)

com.sensirion.smartgadget.tests.ui.view.XyPlotViewGridTest > testCorners[GT-I9505 - 4.4.2] FAILED 
    junit.framework.AssertionFailedError
    at com.sensirion.smartgadget.tests.ui.view.XyPlotViewGridTest.testCorners(XyPlotViewGridTest.java:33)

com.sensirion.smartgadget.tests.ui.view.XyPlotViewGridTest > testOutsideGrid[GT-I9505 - 4.4.2] FAILED 
    junit.framework.AssertionFailedError
    at com.sensirion.smartgadget.tests.ui.view.XyPlotViewGridTest.testOutsideGrid(XyPlotViewGridTest.java:46)
:app:connectedDebugAndroidTest FAILED
```

**Comment by xavier-fernandez** [comment]
@abrauchli that test do not pass, these test already failed when I arrived to Sensirion.

That test are not related to this PR.

**Comment by abrauchli** [comment]
I see. The goal (ticket) is still to have them fixed, if possible.
Let's put it off until after the refactoring, then I'll merge this and the new commit (it's a good idea to keep them separate commits on the same branch since this is already reviewed)

**Comment by abrauchli** [comment]
Following discussion, merged as b4fcdc4

**Pull request closed without merging**
